/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizgame;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static models.AccountPlayerModifier.*;
import quizgame.RegisterAccountPlayer;
import ht.LoginAccountAdmin;
import static quizgame.Start.*;
import static connect.ConnectModifier.*;
import ht.Tam;
import javax.swing.JOptionPane;

/**
 *
 * @author THANH
 */
public class LoginAccountPlayer extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginAccountPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldPhoneNumberLogin = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonLoginAdmin = new javax.swing.JButton();
        jPasswordFieldPasswordLogin = new javax.swing.JPasswordField();
        jButtonForgotPassword = new javax.swing.JButton();
        jLabelLoginPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");
        setResizable(false);

        jLabelPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelPhoneNumber.setText("Phone number");

        jTextFieldPhoneNumberLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelPassword.setText("Password");

        jButtonRegister.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLoginAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonLoginAdmin.setText("Login with admin account");
        jButtonLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginAdminActionPerformed(evt);
            }
        });

        jPasswordFieldPasswordLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonForgotPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonForgotPassword.setText("Forgot Password");
        jButtonForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForgotPasswordActionPerformed(evt);
            }
        });

        jLabelLoginPlayer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelLoginPlayer.setText("Login Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButtonLogin)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonForgotPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhoneNumber)
                            .addComponent(jLabelPassword))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPhoneNumberLogin)
                            .addComponent(jPasswordFieldPasswordLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLoginAdmin)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabelLoginPlayer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelLoginPlayer)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumberLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonForgotPassword))
                .addGap(79, 79, 79)
                .addComponent(jButtonLoginAdmin)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (jTextFieldPhoneNumberLogin.getText().length() == 0
                || jPasswordFieldPasswordLogin.getPassword().length == 0) {
            jLabelError.setText("Please fill in all information!!");
        } else {
            if (loginAccPlayer()) {
                String a = jTextFieldPhoneNumberLogin.getText();
                Tam.tampplayer = Integer.parseInt(a);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Welcome " + fullname, "Welcome", JOptionPane.PLAIN_MESSAGE);
                Start start = new Start();
                start.setLocationRelativeTo(null);
                start.setVisible(true);
            } else {
                jLabelError.setText("Incorrect phone number or password.");
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        RegisterAccountPlayer registerAccountPlayer = new RegisterAccountPlayer();
        registerAccountPlayer.setLocationRelativeTo(null);
        registerAccountPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginAdminActionPerformed
        LoginAccountAdmin loginAccountAdmin = new LoginAccountAdmin();
        loginAccountAdmin.setLocationRelativeTo(null);
        loginAccountAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLoginAdminActionPerformed

    private void jButtonForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordActionPerformed
        ForgotPasswordPlayer forgotPasswordPlayer = new ForgotPasswordPlayer();
        forgotPasswordPlayer.setLocationRelativeTo(null);
        forgotPasswordPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonForgotPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginAccountPlayer loginAccountPlayer = new LoginAccountPlayer();
                loginAccountPlayer.setLocationRelativeTo(null);
                loginAccountPlayer.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForgotPassword;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLoginAdmin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelLoginPlayer;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPhoneNumber;
    public static javax.swing.JPasswordField jPasswordFieldPasswordLogin;
    public static javax.swing.JTextField jTextFieldPhoneNumberLogin;
    // End of variables declaration//GEN-END:variables
}
