/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizgame;

/**
 *
 * @author THANH
 */
import static connect.ConnectModifier.*;
import static quizgame.PlayGame.*;
import static quizgame.FeedbackPlayer.*;
import static quizgame.Rank.*;
import static quizgame.HistoryPlay.*;
import static models.AccountPlayerModifier.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        jButtonAccountPlayer.setText(fullname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        jButtonRank = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();
        jButtonAccountPlayer = new javax.swing.JButton();
        jButtonFeedback = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonRules = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");
        setResizable(false);

        jButtonStart.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonRank.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonRank.setText("Rank");
        jButtonRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRankActionPerformed(evt);
            }
        });

        jButtonHistory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonHistory.setText("Play History");
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });

        jButtonAccountPlayer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonAccountPlayer.setText("Player's name");
        jButtonAccountPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccountPlayerActionPerformed(evt);
            }
        });

        jButtonFeedback.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFeedback.setText("Feedback");
        jButtonFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedbackActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonLogout.setText("Log out");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonRules.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonRules.setText("Rules of the game");
        jButtonRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRulesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonRank)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHistory)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFeedback)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonAccountPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRank)
                    .addComponent(jButtonHistory)
                    .addComponent(jButtonFeedback)
                    .addComponent(jButtonAccountPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonRules))
                .addGap(135, 135, 135)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if (checkStatusPlayer()) {
            PlayGame playGame = new PlayGame();
            playGame.setLocationRelativeTo(null);
            playGame.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Your account is currently blocked due to long inactivity."
                    + "\nIf you want to unblock, please inform admin through feedback, admin will unblock your account.",
                    "Notice of account lockout", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
        HistoryPlay historyPlay = new HistoryPlay();
        historyPlay.setLocationRelativeTo(null);
        historyPlay.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jButtonAccountPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccountPlayerActionPerformed
        ChangeInfoPlayer changeInfoPlayer = new ChangeInfoPlayer();
        changeInfoPlayer.setLocationRelativeTo(null);
        changeInfoPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAccountPlayerActionPerformed

    private void jButtonRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRankActionPerformed
        Rank rank = new Rank();
        rank.setLocationRelativeTo(null);
        rank.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRankActionPerformed

    private void jButtonFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedbackActionPerformed
        FeedbackPlayer feedbackPlayer = new FeedbackPlayer();
        feedbackPlayer.setLocationRelativeTo(null);
        feedbackPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFeedbackActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        LoginAccountPlayer loginAccountPlayer = new LoginAccountPlayer();
        loginAccountPlayer.setLocationRelativeTo(null);
        loginAccountPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRulesActionPerformed
        Rules rules = new Rules();
        rules.setLocationRelativeTo(null);
        rules.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Start start = new Start();
                start.setLocationRelativeTo(null);
                start.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonAccountPlayer;
    private javax.swing.JButton jButtonFeedback;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRank;
    private javax.swing.JButton jButtonRules;
    private javax.swing.JButton jButtonStart;
    // End of variables declaration//GEN-END:variables
}
