/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht;

import static connect.ConnectModifier.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AccountPlayer extends javax.swing.JFrame {

    /**
     * Creates new form AccountPlayer
     */
    public AccountPlayer() {
        initComponents();
        show_AP();
    }
    //--------------

    public ArrayList<AP> SearchListAP() {
        createConnection();
        String value = jTextFieldSearch.getText();
        PreparedStatement ps = null;
        ResultSet rs = null;
        Statement st = null;
        ArrayList<AP> SearchListAP = new ArrayList<>();
        try {
            String sql1 = "SELECT * FROM AccountPlayer WHERE CONCAT(AccPlayerID, Phone, Email, Fullname, Gender, Status) LIKE '%" + value + "%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql1);
            AP ap;

            while (rs.next()) {
                ap = new AP(rs.getInt("AccPlayerID"), rs.getInt("Phone"), rs.getString("Email"), rs.getString("Fullname"), rs.getString("Gender"), rs.getInt("Status"));
                SearchListAP.add(ap);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return SearchListAP;
    }

    public void show_SearchAP() {
        ArrayList<AP> list = SearchListAP();
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getAccPlayerID();
            row[1] = list.get(i).getPhone();
            row[2] = list.get(i).getEmail();
            row[3] = list.get(i).getFullname();
            row[4] = list.get(i).getGender();
            row[5] = list.get(i).getStatus();
            model.addRow(row);
        }
    }

    //--------------
    public ArrayList<AP> APList() {
        createConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        Statement st = null;
        ArrayList<AP> APList = new ArrayList<>();
        try {
            String sql1 = "SELECT * FROM AccountPlayer";
            st = conn.createStatement();
            rs = st.executeQuery(sql1);
            AP ap;

            while (rs.next()) {
                ap = new AP(rs.getInt("AccPlayerID"), rs.getInt("Phone"), rs.getString("Email"), rs.getString("Fullname"), rs.getString("Gender"), rs.getInt("Status"));
                APList.add(ap);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return APList;
    }

    public void show_AP() {
        ArrayList<AP> list = APList();
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getAccPlayerID();
            row[1] = list.get(i).getPhone();
            row[2] = list.get(i).getEmail();
            row[3] = list.get(i).getFullname();
            row[4] = list.get(i).getGender();
            row[5] = list.get(i).getStatus();
            model.addRow(row);
        }
    }

    //--------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccountPlayer = new javax.swing.JTable();
        jButtonBlock = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonUnBlock = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jLabelManageAccountPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");

        jTableAccountPlayer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableAccountPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Phone", "Email", "Fullname", "Gender", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableAccountPlayer);

        jButtonBlock.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonBlock.setText("Block Account");
        jButtonBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlockActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonUnBlock.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonUnBlock.setText("UnBlock Account");
        jButtonUnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnBlockActionPerformed(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/secrch.png"))); // NOI18N

        jButtonRefresh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jLabelManageAccountPlayer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelManageAccountPlayer.setText("Manage Account Player");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBack))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelManageAccountPlayer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonBlock)
                                        .addGap(93, 93, 93)
                                        .addComponent(jButtonUnBlock)
                                        .addGap(73, 73, 73))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonRefresh)
                                            .addComponent(jButtonSearch))))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jLabelManageAccountPlayer))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRefresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBlock)
                    .addComponent(jButtonUnBlock))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainAdmin mainAdmin = new MainAdmin();
        mainAdmin.setLocationRelativeTo(null);
        mainAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonUnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnBlockActionPerformed
        createConnection();
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        int i = jTableAccountPlayer.getSelectedRow();
        String id = model.getValueAt(i, 0).toString();
        int value = Integer.parseInt(id);
        JFrame frame = new JFrame();
        int n = JOptionPane.showConfirmDialog(frame, "Do you want to unblock this account?", "System", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            try {
                String query = "UPDATE AccountPlayer SET Status=1 WHERE AccPlayerID =" + value;
                PreparedStatement ps = conn.prepareStatement(query);
                ps.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
            //load lai bảng
            model.setRowCount(0);
            show_AP();
        }
    }//GEN-LAST:event_jButtonUnBlockActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        model.setRowCount(0);
        show_SearchAP();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        model.setRowCount(0);
        show_AP();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlockActionPerformed
        createConnection();
        DefaultTableModel model = (DefaultTableModel) jTableAccountPlayer.getModel();
        int i = jTableAccountPlayer.getSelectedRow();
        String id = model.getValueAt(i, 0).toString();
        int value = Integer.parseInt(id);
        JFrame frame = new JFrame();
        int n = JOptionPane.showConfirmDialog(frame, "Do you want to block this account?", "System", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            try {
                String query = "UPDATE AccountPlayer SET Status=0 WHERE AccPlayerID =" + value;
                PreparedStatement ps = conn.prepareStatement(query);
                ps.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
            //load lai bảng
            model.setRowCount(0);
            show_AP();
        }
    }//GEN-LAST:event_jButtonBlockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccountPlayer accountPlayer = new AccountPlayer();
                accountPlayer.setLocationRelativeTo(null);
                accountPlayer.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBlock;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUnBlock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelManageAccountPlayer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccountPlayer;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
