/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht;

import static connect.ConnectModifier.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class AddQuestion extends javax.swing.JFrame {

    String gender;

    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jLabelAddQuestion = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabelRightAnswer = new javax.swing.JLabel();
        jButtonAddQuestion = new javax.swing.JButton();
        jComboBoxLevel = new javax.swing.JComboBox<>();
        jComboBoxRightAnswer = new javax.swing.JComboBox<>();
        jLabelLevel = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jLabelB = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jLabelC = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jLabelD = new javax.swing.JLabel();
        jTextFieldD = new javax.swing.JTextField();
        jTextFieldQuestion = new javax.swing.JTextField();
        jLabelQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelAddQuestion.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelAddQuestion.setText("Add Question");

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelRightAnswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelRightAnswer.setText("Right Answer:");

        jButtonAddQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonAddQuestion.setText("Add");
        jButtonAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQuestionActionPerformed(evt);
            }
        });

        jComboBoxLevel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jComboBoxRightAnswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxRightAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jLabelLevel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelLevel.setText("Level:");

        jLabelA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelA.setText("Answer A:");

        jTextFieldA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelB.setText("Answer B:");

        jTextFieldB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelC.setText("Answer C:");

        jTextFieldC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelD.setText("Answer D:");

        jTextFieldD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelQuestion.setText("Question:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(jLabelAddQuestion)
                        .addGap(224, 224, 224)
                        .addComponent(jButtonReset))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQuestion)
                                    .addComponent(jLabelB)
                                    .addComponent(jLabelA))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQuestion)
                                    .addComponent(jTextFieldA)
                                    .addComponent(jTextFieldB)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelD)
                                    .addComponent(jLabelC))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldC)
                                    .addComponent(jTextFieldD)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabelRightAnswer)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLevel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonBack)
                    .addComponent(jLabelAddQuestion))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestion)
                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelA)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelB)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelC)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelD)
                    .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRightAnswer)
                    .addComponent(jComboBoxRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLevel)
                    .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAddQuestion)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldQuestion.setText("");
        jTextFieldA.setText("");
        jTextFieldB.setText("");
        jTextFieldC.setText("");
        jTextFieldD.setText("");
        jComboBoxRightAnswer.setSelectedIndex(0);
        jComboBoxLevel.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        QuestionAdmin questionAdmin = new QuestionAdmin();
        questionAdmin.setLocationRelativeTo(null);
        questionAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQuestionActionPerformed
        createConnection();

        String daua = "A. ";
        String daub = "B. ";
        String dauc = "C. ";
        String daud = "D. ";

        String qs = jTextFieldQuestion.getText();
        String aa = jTextFieldA.getText();
        String ab = jTextFieldB.getText();
        String ac = jTextFieldC.getText();
        String ad = jTextFieldD.getText();
        StringBuilder sb = new StringBuilder();

        //kiem tra trong cac o text
        if (qs.equals("")) {
            sb.append("Please check Question can't be empty !\n");
        }
        if (aa.equals("")) {
            sb.append("Please check Answer A can't be empty !\n");
        }
        if (ab.equals("")) {
            sb.append("Please check Answer B can't be empty !\n");
        }
        if (ac.equals("")) {
            sb.append("Please check Answer C can't be empty !\n");
        }
        if (ad.equals("")) {
            sb.append("Please check Answer D can't be empty !\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "System", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String query = "insert into Questions ([Question], [Answer1], [Answer2], [Answer3], [Answer4], [RightAnswer], [Level])"
                        + "values (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(query);

                //cong chuoi de co A. dau cau tra loi 
                String a = daua + aa;
                String b = daub + ab;
                String c = dauc + ac;
                String d = daud + ad;

                ps.setString(1, jTextFieldQuestion.getText());
                ps.setString(2, a);
                ps.setString(3, b);
                ps.setString(4, c);
                ps.setString(5, d);

                String course;
                course = jComboBoxRightAnswer.getSelectedItem().toString();
                ps.setString(6, course);

                String course1;
                course1 = jComboBoxLevel.getSelectedItem().toString();
                ps.setInt(7, Integer.parseInt(course1));
                ps.executeUpdate();

                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                        "Add success !");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButtonAddQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddQuestion addQuestion = new AddQuestion();
                addQuestion.setLocationRelativeTo(null);
                addQuestion.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JComboBox<String> jComboBoxRightAnswer;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelAddQuestion;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelRightAnswer;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldD;
    private javax.swing.JTextField jTextFieldQuestion;
    // End of variables declaration//GEN-END:variables
}
