/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht;

import static connect.ConnectModifier.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class QuestionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form QuestionAdmin
     */
    public QuestionAdmin() {
        initComponents();
        show_QA();
    }

    //----------------------------------
    public ArrayList<QA> QAList() {
        createConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        Statement st = null;
        ArrayList<QA> QAList = new ArrayList<>();
        try {
            String sql1 = "SELECT * FROM Questions";
            st = conn.createStatement();
            rs = st.executeQuery(sql1);
            QA qa;

            while (rs.next()) {
                qa = new QA(rs.getInt("QuesID"), rs.getString("Question"), rs.getString("Answer1"), rs.getString("Answer2"), rs.getString("Answer3"), rs.getString("Answer4"), rs.getString("RightAnswer"), rs.getInt("Level"));
                QAList.add(qa);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return QAList;
    }

    public void show_QA() {
        ArrayList<QA> list = QAList();
        DefaultTableModel model = (DefaultTableModel) jTableQuestionAndAnswer.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getQuesID();
            row[1] = list.get(i).getQuestion();
            row[2] = list.get(i).getAnswer1();
            row[3] = list.get(i).getAnswer2();
            row[4] = list.get(i).getAnswer3();
            row[5] = list.get(i).getAnswer4();
            row[6] = list.get(i).getRightAnswer();
            row[7] = list.get(i).getLevel();
            model.addRow(row);
        }
    }

    //---------------------------------
    public ArrayList<QA> SearchList() {
        String value = jTextFieldSearch.getText();
        createConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        Statement st = null;
        ArrayList<QA> SearchList = new ArrayList<>();
        try {
            String sql1 = "SELECT * FROM Questions WHERE CONCAT(QuesID, Question, Answer1, Answer2, Answer3, Answer4) LIKE '%" + value + "%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql1);
            QA qa;

            while (rs.next()) {
                qa = new QA(rs.getInt("QuesID"), rs.getString("Question"), rs.getString("Answer1"), rs.getString("Answer2"), rs.getString("Answer3"), rs.getString("Answer4"), rs.getString("RightAnswer"), rs.getInt("Level"));
                SearchList.add(qa);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return SearchList;
    }

    public void show_Search() {
        ArrayList<QA> list = SearchList();
        DefaultTableModel model = (DefaultTableModel) jTableQuestionAndAnswer.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getQuesID();
            row[1] = list.get(i).getQuestion();
            row[2] = list.get(i).getAnswer1();
            row[3] = list.get(i).getAnswer2();
            row[4] = list.get(i).getAnswer3();
            row[5] = list.get(i).getAnswer4();
            row[6] = list.get(i).getRightAnswer();
            row[7] = list.get(i).getLevel();
            model.addRow(row);
        }
    }

    //----------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelQuestionAndAnswer = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuestionAndAnswer = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/secrch.png"))); // NOI18N

        jTextFieldSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelQuestionAndAnswer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQuestionAndAnswer.setText("Questions and answers");

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTableQuestionAndAnswer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Question", "Answer 1", "Answer 2", "Answer 3", "Answer 4", "Right Answer ", "Level"
            }
        ));
        jTableQuestionAndAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuestionAndAnswerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuestionAndAnswer);

        jButtonRefresh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addGap(117, 117, 117)
                                .addComponent(jLabelQuestionAndAnswer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jButtonSearch))
                                    .addComponent(jButtonRefresh))))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jLabelQuestionAndAnswer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRefresh)
                            .addComponent(jButtonAdd))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(483, 483, 483))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainAdmin mainAdmin = new MainAdmin();
        mainAdmin.setLocationRelativeTo(null);
        mainAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        AddQuestion addQuestion = new AddQuestion();
        addQuestion.setLocationRelativeTo(null);
        addQuestion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTableQuestionAndAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuestionAndAnswerMouseClicked
        UpdateQuestion jtRowData = new UpdateQuestion();

        int i = jTableQuestionAndAnswer.getSelectedRow();
        TableModel model = jTableQuestionAndAnswer.getModel();
        String id = model.getValueAt(i, 0).toString();
        String question = model.getValueAt(i, 1).toString();
        String answer1 = model.getValueAt(i, 2).toString();
        String answer2 = model.getValueAt(i, 3).toString();
        String answer3 = model.getValueAt(i, 4).toString();
        String answer4 = model.getValueAt(i, 5).toString();
        String rightanswer = model.getValueAt(i, 6).toString();
        String level = model.getValueAt(i, 7).toString();

        jtRowData.setVisible(true);
        jtRowData.setLocationRelativeTo(null);
        this.setVisible(false);
        jtRowData.pack();
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jtRowData.jLabelID.setText(id);
        jtRowData.jTextFieldQuestion.setText(question);
        jtRowData.jTextFieldA.setText(answer1.substring(3));
        jtRowData.jTextFieldB.setText(answer2.substring(3));
        jtRowData.jTextFieldC.setText(answer3.substring(3));
        jtRowData.jTextFieldD.setText(answer4.substring(3));
        switch (rightanswer) {
            case "A":
                jtRowData.jComboBoxRightAnswer.setSelectedIndex(0);
                break;
            case "B":
                jtRowData.jComboBoxRightAnswer.setSelectedIndex(1);
                break;
            case "C":
                jtRowData.jComboBoxRightAnswer.setSelectedIndex(2);
                break;
            case "D":
                jtRowData.jComboBoxRightAnswer.setSelectedIndex(3);
                break;
        }
        switch (level) {
            case "1":
                jtRowData.jComboBoxLevel.setSelectedIndex(0);
                break;
            case "2":
                jtRowData.jComboBoxLevel.setSelectedIndex(1);
                break;
            case "3":
                jtRowData.jComboBoxLevel.setSelectedIndex(2);
                break;
        }
    }//GEN-LAST:event_jTableQuestionAndAnswerMouseClicked

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableQuestionAndAnswer.getModel();
        model.setRowCount(0);
        show_QA();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableQuestionAndAnswer.getModel();
        model.setRowCount(0);
        show_Search();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuestionAdmin questionAdmin = new QuestionAdmin();
                questionAdmin.setLocationRelativeTo(null);
                questionAdmin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelQuestionAndAnswer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableQuestionAndAnswer;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
