/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht;

import static connect.ConnectModifier.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class UpdateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form UpdateQuestion
     */
    public UpdateQuestion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jLabelUpdateQuestion = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jTextFieldB = new javax.swing.JTextField();
        jTextFieldC = new javax.swing.JTextField();
        jTextFieldD = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jComboBoxRightAnswer = new javax.swing.JComboBox<>();
        jComboBoxLevel = new javax.swing.JComboBox<>();
        jLabelRightAnswer = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelIDQuestion = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game Online");

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelUpdateQuestion.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelUpdateQuestion.setText("Update Question");
        jLabelUpdateQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelQuestion.setText("Question:");

        jTextFieldQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelA.setText("Answer A:");

        jLabelB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelB.setText("Answer B:");

        jLabelC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelC.setText("Answer C:");

        jLabelD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelD.setText("Answer D:");

        jTextFieldA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonUpdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jComboBoxRightAnswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxRightAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jComboBoxLevel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabelRightAnswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelRightAnswer.setText("Right Answer:");

        jLabelLevel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelLevel.setText("Level:");

        jButtonDelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonDelete.setText("Delete Question");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelIDQuestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelIDQuestion.setText("ID Question:");

        jLabelID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelID.setText("?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(jLabelUpdateQuestion)
                        .addGap(127, 127, 127)
                        .addComponent(jButtonDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelQuestion)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldQuestion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIDQuestion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelID)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldB))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldC))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabelRightAnswer)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225)
                        .addComponent(jLabelLevel)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonUpdate)
                .addGap(365, 365, 365))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUpdateQuestion)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonBack))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDQuestion)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestion)
                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelA)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelB)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelC)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelD)
                    .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRightAnswer)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelLevel)
                        .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        QuestionAdmin questionAdmin = new QuestionAdmin();
        questionAdmin.setLocationRelativeTo(null);
        questionAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // o day la test
        createConnection();
        String idq = jLabelID.getText();
        JFrame frame = new JFrame();
        int n = JOptionPane.showConfirmDialog(frame, "Do you want to delete the question ?", "Delete", JOptionPane.YES_NO_OPTION);
        if (n == 0) {

            try {
                int value = Integer.parseInt(idq);
                String query = "DELETE FROM Questions WHERE QuesID=" + value;
                PreparedStatement ps = conn.prepareStatement(query);
                ps.executeUpdate();

                QuestionAdmin qa = new QuestionAdmin();
                qa.setLocationRelativeTo(null);
                qa.setVisible(true);
                this.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        QuestionAdmin jtTableData = new QuestionAdmin();
        createConnection();

        String daua = "A. ";
        String daub = "B. ";
        String dauc = "C. ";
        String daud = "D. ";

        String idq = jLabelID.getText();
        String qs = jTextFieldQuestion.getText();
        String aa = jTextFieldA.getText();
        String ab = jTextFieldB.getText();
        String ac = jTextFieldC.getText();
        String ad = jTextFieldD.getText();
        StringBuilder sb = new StringBuilder();

        //kiem tra trong cac o text
        if (qs.equals("")) {
            sb.append("Please check Question can't be empty !\n");
        }
        if (aa.equals("")) {
            sb.append("Please check Answer A can't be empty !\n");
        }
        if (ab.equals("")) {
            sb.append("Please check Answer B can't be empty !\n");
        }
        if (ac.equals("")) {
            sb.append("Please check Answer C can't be empty !\n");
        }
        if (ad.equals("")) {
            sb.append("Please check Answer D can't be empty !\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "System", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int value = Integer.parseInt(idq);
                String query = "UPDATE Questions SET Question=?, Answer1=?, Answer2=?, Answer3=?, Answer4=?, RightAnswer=?, Level=? WHERE QuesID =" + value;
                PreparedStatement ps = conn.prepareStatement(query);

//            cong chuoi de co A. dau cau tra loi 
                String a = daua + aa;
                String b = daub + ab;
                String c = dauc + ac;
                String d = daud + ad;

                ps.setString(1, jTextFieldQuestion.getText());
                ps.setString(2, a);
                ps.setString(3, b);
                ps.setString(4, c);
                ps.setString(5, d);

                String course;
                course = jComboBoxRightAnswer.getSelectedItem().toString();
                ps.setString(6, course);

                String course1;
                course1 = jComboBoxLevel.getSelectedItem().toString();
                ps.setInt(7, Integer.parseInt(course1));
                ps.executeUpdate();

                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                        "Update success !");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateQuestion updateQuestion = new UpdateQuestion();
                updateQuestion.setLocationRelativeTo(null);
                updateQuestion.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    public javax.swing.JComboBox<String> jComboBoxLevel;
    public javax.swing.JComboBox<String> jComboBoxRightAnswer;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelD;
    public javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDQuestion;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelRightAnswer;
    private javax.swing.JLabel jLabelUpdateQuestion;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldA;
    public javax.swing.JTextField jTextFieldB;
    public javax.swing.JTextField jTextFieldC;
    public javax.swing.JTextField jTextFieldD;
    public javax.swing.JTextField jTextFieldQuestion;
    // End of variables declaration//GEN-END:variables
}
